version: '3.8'

services:
  backend:
    container_name: nestjs_api_dev
    build:
      context: .
      target: development
      dockerfile: ./backend/Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  # backend_prod:
  #   container_name: nestjs_api_prod
  #   build:
  #     context: .
  #     target: production
  #     dockerfile: ./backend/Dockerfile
  #   command: npm run start:prod
  #   ports:
  #     - 3001:3000
  #   networks:
  #     - nestjs-network
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped

  frontend:
    container_name: vuejs_frontend
    build:
      context: ./frontend
    ports:
      - '80:80'
    networks:
      - nestjs-network
    volumes:
      - ./frontend:/app

networks:
  nestjs-network:
    driver: bridge
